# Generated by Django 3.2.7 on 2021-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(max_length=30)),
                ('Duration', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
